[project]
name = "airbnb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Avinash Patel", email = "avinashjpatel19@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dbt-core>=1.12.5",
    "dbt-snowflake>=1.12.1",
]

[project.scripts]
airbnb = "airbnb:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
